<?php
// Copyright 1999-2018. Plesk International GmbH. All rights reserved.

echo '<p>' . \pm_Locale::lmsg('pageDescription') . '</p>';

if ($this->isEmptyDir) {
    if (!$this->runningTask) {
        echo '<p style="text-align: center;">' . htmlspecialchars(\pm_Locale::lmsg('messageEmptyDir')) . '</p>';
    }
} else {
    echo '<div id="piechart" style="width: 800px; height: 400px;"></div>';

    echo $this->renderList($this->list);
}

?>

<script>
function extDiskspaceUsageViewerRefresh(path) {
    new Ajax.Request('/modules/diskspace-usage-viewer/index.php/index/refresh?path=' + encodeURIComponent(path), {
        method: 'post',
        onSuccess: function (resp) {
            Jsw.getComponent('asyncProgressBarWrapper').progressDialog(resp.responseJSON);
        }
    });
}

<?php if (!$this->isEmptyDir): ?>
google.charts.load('current', {'packages':['corechart']});

google.charts.setOnLoadCallback(function () {
    var data = new google.visualization.DataTable();

    data.addColumn('string', 'Name');
    data.addColumn('number', 'Size');
    data.addColumn({type: 'string', role: 'tooltip'});

    data.addRows(<?= json_encode($this->chartData); ?>);

    var options = {
        title: '',
        is3D: true
    };

    var chart = new google.visualization.PieChart(document.getElementById('piechart'));

    chart.draw(data, options);
});
<?php endif ?>

<?php if ($this->runningTask): ?>
Jsw.onReady(function () {
    Jsw.getComponent('asyncProgressBarWrapper').progressDialog(<?= json_encode($this->runningTask->toArray()) ?>);
});
<?php endif ?>
</script>
