<?php
// Copyright 1999-2018. Plesk International GmbH. All rights reserved.

function formatBytes(int $bytes): string
{
    if ($bytes == 0) {
        return '0 B';
    }

    $k = 1024;
    $sizes = ['B', 'KB', 'MB', 'GB', 'TB', 'PB', 'EB', 'ZB', 'YB'];
    $i = floor(log($bytes) / log($k));

    return round($bytes / pow($k, $i)) . ' ' . $sizes[$i];
}

$translationStrings = array_merge(
    \pm_Locale::getSection('home')
);
?>
<div id="ext-<?= \pm_Context::getModuleId() ?>-app"></div>

<script>
    require(['<?= \pm_Context::getBaseUrl() ?>js/main.js'], function(render) {
        render(document.getElementById('ext-<?= \pm_Context::getModuleId() ?>-app'), <?= json_encode([
            'action'          => 'home',
            'locales'         => $translationStrings,
            'list'            => $this->items,
            'path'            => $this->path,
            'breadcrumbsPath' => $this->breadcrumbsPath,
        ]) ?>);
    });
</script>